// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBasePath(arg1) {
  return window['go']['main']['App']['GetBasePath'](arg1);
}

export function GetVideos(arg1) {
  return window['go']['main']['App']['GetVideos'](arg1);
}
