// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DirDialog():Promise<string>;

export function GetBasePath(arg1:string):Promise<string>;

export function GetVideos(arg1:string):Promise<Array<string>>;
