// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBasePath():Promise<string>;

export function GetVideos():Promise<Array<string>>;
