name: Wails build and release
# Copied from https://wails.io/docs/guides/crossplatform-build/

on:
  push:
    tags:
      - 'v*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'viewparty-x64'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'viewparty-arm64'
            platform: 'linux/arm64'
            os: 'ubuntu-24.04-arm'
          - name: 'viewparty-x64'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'viewparty-arm64'
            platform: 'windows/arm64'
            os: 'windows-11-arm'
          - name: 'viewparty'
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.25'
