name: Wails build and release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'viewparty-linux-x64'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'viewparty-linux-arm64'
            platform: 'linux/arm64'
            os: 'ubuntu-24.04-arm'
          - name: 'viewparty-windows'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'viewparty' # macos won't build properly with a different name parameter
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.25'

      # Upload build assets ourselves, since `package` param above was kept false to prevent release creation
      - uses: actions/upload-artifact@v4
        with:
          name: Wails Build ${{runner.os}} ${{matrix.build.name}}
          path: |
            */bin/
            *\bin\*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: build-assets
          merge-multiple: true

      - run: ls -R build-assets

      - run: mv build-assets/build/bin/viewparty.pkg build-assets/build/bin/viewparty-macos.pkg

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          # just giving explicit paths should work,
          # but we could also rm the files we don't want to include and then match these with *
          files: |
            build-assets/build/bin/viewparty-linux-x64
            build-assets/build/bin/viewparty-linux-arm64
            build-assets/build/bin/viewparty-windows-x64
            build-assets/build/bin/viewparty-macos.pkg
          generate_release_notes: true
